# permissions for end users to view resourcecreators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcecreator-viewer-role
rules:
- apiGroups:
  - api.adityajoshi.online
  resources:
  - resourcecreators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.adityajoshi.online
  resources:
  - resourcecreators/status
  verbs:
  - get
